#!/bin/sh

# PROVIDE: LUNA
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# LUNA_enable (bool): Set to NO by default. Set this variable to YES if you want to enable LUNA service.
# LUNA_config (path): Set to /usr/local/etc/LUNA.conf by default.
# LUNA_user:  The user account LUNA daemon runs as. It uses 'root' user by default.
# LUNA_group: The group account LUNA daemon runs as. It uses 'wheel' group by default.
# LUNA_datadir (str): Default to "/var/db/LUNA". Base data directory.

. /etc/rc.subr

name=LUNA
rcvar=LUNA_enable

: ${LUNA_enable:=NO}
: ${LUNA_config=/usr/local/etc/LUNA.conf}
: ${LUNA_datadir=/var/db/LUNA}
: ${LUNA_user="root"}
: ${LUNA_group="wheel"}

required_files=${LUNA_config}
command=/usr/local/bin/LUNAd
LUNA_chdir=${LUNA_datadir}
pidfile="${LUNA_datadir}/LUNAd.pid"
stop_cmd=LUNA_stop
command_args="-conf=${LUNA_config} -datadir=${LUNA_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

LUNA_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${LUNA_datadir}
	[ $? -eq 0 ] && chown -R ${LUNA_user}:${LUNA_group} ${LUNA_datadir}
}

LUNA_prestart()
{
	if [ ! -d "${LUNA_datadir}/." ]; then
		LUNA_create_datadir || return 1
	fi
}

LUNA_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

LUNA_stop()
{
    LUNA_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${LUNA_config} -datadir=${LUNA_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
